name: Publish blog

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Clone latest source code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Configure npm registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: pnpm install

      - name: Build the website
        run: pnpm run build

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/blog/dist
          commit_message: ${{ github.event.head_commit.message }}
          cname: blog.bichls.dev
          user_name: "github-actions[bot]"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
